# -*- coding: utf-8 -*-
"""Data_Augmentation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OxneE9HWPDtGLJP79zLDpaJskw2H_BS2
"""

!git clone https://github.com/allenai/PeerRead.git

!gdown --folder https://drive.google.com/drive/folders/1CAbb3DjrOPBNm0ozVBfhvrEh9P9rAppc

import os
import pandas as pd

base_path = '/content/PeerRead/data/'
all_extracted_comments = []

# Iterate through each conference directory (e.g., acl_2017, naacl_2016)
for conference_dir in os.listdir(base_path):
    conference_path = os.path.join(base_path, conference_dir)
    if os.path.isdir(conference_path):
        # Iterate through train, dev, test subdirectories
        for split_type in ['train', 'dev', 'test']:
            split_path = os.path.join(conference_path, split_type, 'reviews')
            if os.path.isdir(split_path):
                # Iterate through each JSON file in the reviews directory
                for json_file in os.listdir(split_path):
                    if json_file.endswith('.json'):
                        file_path = os.path.join(split_path, json_file)
                        try:
                            # Read the JSON file
                            df_temp = pd.read_json(file_path, lines=True)

                            # Extract comments from the 'reviews' column
                            if 'reviews' in df_temp.columns:
                                for index, row in df_temp.iterrows():
                                    if isinstance(row['reviews'], list):
                                        for review_item in row['reviews']:
                                            if isinstance(review_item, dict) and 'comments' in review_item:
                                                all_extracted_comments.append(review_item['comments'])
                        except Exception as e:
                            print(f"Error processing {file_path}: {e}")

# Create the final DataFrame
final_comments_df = pd.DataFrame({"text": all_extracted_comments})
final_comments_df["label"] = 0
final_comments_df["source"] = "peerread"

print("DataFrame created successfully!")
print(final_comments_df.head())
print(final_comments_df.info())

df_train = pd.read_json("/content/SubtaskA/subtaskA_train_monolingual.jsonl", lines=True)
df_train = df_train.drop(columns=["id"])
df_train.head(3)

df2 = pd.read_json("/content/text_generated.json")
df2.head()

import re
import pandas as pd

# --- Yêu cầu 1: Làm sạch dữ liệu văn bản (Advanced Text Cleaning với Regex) ---
def clean_text(text):
    text = str(text) # Đảm bảo text là kiểu chuỗi để tránh lỗi

    # Bước 1. Truncation (Cắt bỏ phần đuôi bài viết)
    # Các từ khóa: "References", "External links", "See also", "Further reading", "Bibliography".
    # Điều kiện: Các từ này phải đứng ở đầu một dòng (có thể có ký tự khoảng trắng hoặc dấu markdown).
    # Hành động: Xóa tiêu đề đó và toàn bộ phần văn bản từ đó cho đến cuối chuỗi.
    truncation_keywords = [
        'References', 'External links', 'See also',
        'Further reading', 'Bibliography'
    ]
    # Xây dựng pattern regex để tìm bất kỳ từ khóa nào ở đầu dòng
    # ^\s*[=\-#*]*\s* : Khớp với khoảng trắng, dấu markdown (==, ###, *) ở đầu dòng.
    # (?:...) : Nhóm không bắt giữ cho các từ khóa.
    # \b : Biên từ, đảm bảo khớp toàn bộ từ khóa chứ không phải một phần.
    truncation_pattern = r'^\s*[=\-#*]*\s*(?:' + '|'.join(re.escape(k) for k in truncation_keywords) + r')\b'

    # Tìm kiếm sự xuất hiện sớm nhất của pattern này (case-insensitive, multi-line)
    match = re.search(truncation_pattern, text, flags=re.IGNORECASE | re.MULTILINE)
    if match:
        # Nếu tìm thấy, cắt bỏ phần văn bản từ vị trí bắt đầu của match trở đi
        text = text[:match.start()]

    # Bước 2. Line Removal (Xóa các dòng/đoạn rác cụ thể)
    # Các từ khóa: "Edit:", "ETA:", "TL;DR", "Tips:", "Warnings:", "Notes:".
    # Điều kiện: Chỉ bắt khi các từ này nằm ở ngay đầu dòng.
    # Hành động: Xóa từ khóa đó và nội dung trên cùng dòng/đoạn đó.
    line_removal_keywords = [
        'Edit:', 'ETA:', 'TL;DR', 'Tips:', 'Warnings:', 'Notes:'
    ]
    # Xây dựng pattern regex để tìm các từ khóa này ở đầu dòng và sau đó khớp toàn bộ dòng
    # ^\s* : Khớp với khoảng trắng ở đầu dòng.
    # (?:...) : Nhóm không bắt giữ cho các từ khóa.
    # .*$ : Khớp bất kỳ ký tự nào cho đến cuối dòng (không bao gồm ký tự xuống dòng).
    line_removal_pattern = r'^\s*(?:' + '|'.join(re.escape(k) for k in line_removal_keywords) + r').*$'
    text = re.sub(line_removal_pattern, '', text, flags=re.IGNORECASE | re.MULTILINE)

    # Bước 3. Xóa HTML/CSS rác
    # Xóa các chuỗi định dạng CSS inline rác như "styleborderleftpx..." và các thẻ HTML thừa nếu có.
    # Xóa các chuỗi CSS inline rác cụ thể (ví dụ: 'styleborderleftpx...')
    # styleborderleftpx[^\s]* : Khớp 'styleborderleftpx' theo sau bởi bất kỳ ký tự nào không phải khoảng trắng.
    text = re.sub(r'styleborderleftpx[^\s]*', '', text, flags=re.IGNORECASE)
    # Xóa các thuộc tính 'style="..."' hoặc 'style=\'...\''
    # style\s*=\s*"[^"]*" : Khớp thuộc tính style với giá trị trong dấu ngoặc kép.
    text = re.sub(r'style\s*=\s*"[^"]*"', '', text, flags=re.IGNORECASE)
    # style\s*=\s*\'[^\']*\'' : Khớp thuộc tính style với giá trị trong dấu ngoặc đơn.
    text = re.sub(r'style\s*=\s*\'[^\']*\'', '', text, flags=re.IGNORECASE)
    # Xóa các thẻ HTML chung
    # <[^>]+> : Khớp bất kỳ chuỗi nào bắt đầu bằng '<', theo sau là một hoặc nhiều ký tự không phải '>', và kết thúc bằng '>'.
    text = re.sub(r'<[^>]+>', '', text)

    return text.strip()

df_train['text'] = df_train['text'].apply(clean_text)
df2['text'] = df2['text'].apply(clean_text)
final_comments_df['text'] = final_comments_df['text'].apply(clean_text)

import pandas as pd
import re

def deep_clean_ai_review(text: str) -> str:
    """
    Hàm dọn dẹp sâu: Xóa văn mẫu kịch tính, placeholder và định dạng rập khuôn của AI.
    """
    patterns = [
        # 1. XÓA CÁC CÂU CẢM THÁN "KỊCH TÍNH" CỦA AI (Xóa đến hết câu chứa dấu chấm)
        # Bắt các câu bắt đầu bằng "I must say,", "I am astonished", "I am underwhelmed"...
        r"(?i)(I must say,\s*)?(I am|I'm)\s*(underwhelmed|astonished|surprised)[^\.]*\.\s*",

        # 2. XÓA PLACEHOLDER
        # Cắt các dòng "Paper Title: [Insert Paper Title]"
        r"(?i)(Paper Title|Authors):\s*\[Insert.*?\].*\n*",
        # Cắt các cụm [Insert...] nằm rải rác
        r"\[Insert.*?\]",

        # 3. XÓA CÁC TIÊU ĐỀ RẬP KHUÔN (Để text trông giống 1 đoạn văn tự nhiên hơn)
        # Bắt các từ như Summary:, Strengths:, Weaknesses:, v.v. đứng đầu dòng
        r"(?i)^(Summary|Overall Assessment|Overall Impression|Strengths|Weaknesses and Suggestions for Improvement|Weaknesses and Suggestions|Minor Comments|Conclusion|Recommendation|Specific Comments|Actionable Suggestions):\s*\n*",

        # 4. Xóa từ Peer Review
        r"\bPeer Review\b",

        # 5. XÓA ĐÁNH SỐ (1. 2. 3.), BULLETS (*, -) VÀ TIÊU ĐỀ PHỤ
        # Sẽ bắt các dạng:
        # "1. Novel Architecture: The model..." -> xóa "1. Novel Architecture: "
        # "* Lack of Ablation: The authors..." -> xóa "* Lack of Ablation: "
        # "2. The results are good." -> xóa "2. "
        r"^[ \t]*(?:\d+\.|\*|\-)\s*(?:[^:\n]+:\s*)?"
    ]

    cleaned_text = str(text)

    # Quét và xóa
    for pattern in patterns:
        # Dùng re.MULTILINE để có thể bắt được các Regex có dấu ^ (đầu dòng)
        cleaned_text = re.sub(pattern, "", cleaned_text, flags=re.IGNORECASE | re.MULTILINE)

    # 4. FIX LỖI CỤT ĐUÔI (Cắt bỏ phần text lở dở ở cuối nếu API sinh thiếu)
    last_punct_idx = max(cleaned_text.rfind('.'), cleaned_text.rfind('!'), cleaned_text.rfind('?'))
    if last_punct_idx != -1:
        cleaned_text = cleaned_text[:last_punct_idx + 1]

    # Xóa các khoảng trắng thừa do việc cắt text để lại
    cleaned_text = re.sub(r'\n{3,}', '\n\n', cleaned_text)

    return cleaned_text.strip()

# Áp dụng hàm dọn dẹp vào cột text
df2["cleaned_text"] = df2["text"].apply(deep_clean_ai_review)

# Xem thử kết quả (So sánh trước và sau khi dọn)
for idx, row in df2.iterrows():
    print(f"Bản gốc : {row['text']}")
    print(f"Đã dọn  : {row['cleaned_text']}")
    print("-" * 50)

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(12, 7))
sns.countplot(data=df_train, x='source', hue='label', palette='viridis')
plt.title('Distribution of Sources by Label (Human vs. Machine)')
plt.xlabel('Source')
plt.ylabel('Count')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

df_train.info()

import pandas as pd
import os

# Prepare final_comments_df (natural reviews)
# Use 'text' column from final_comments_df as 'cleaned_text' for this dataset
df_natural_reviews = pd.DataFrame({
    'text': final_comments_df['text'],
    'label': final_comments_df['label'],
    'source': final_comments_df['source'],
    'model': 'human'
})

# Prepare df2 (AI generated reviews)
# Use 'cleaned_text' column from df2
df_ai_reviews = pd.DataFrame({
    'text': df2['cleaned_text'],
    'label': df2['label'], # Expecting label 1 as per user's instruction
    'source': df2['source'],
    'model': df2['model']
})

# Concatenate all dataframes
combined_df = pd.concat([df_train, df_natural_reviews, df_ai_reviews], ignore_index=True)

# Define the output path
output_path = "/content/drive/MyDrive/cleaned_text_data.jsonl"

# Ensure the directory exists before saving
output_dir = os.path.dirname(output_path)
if not os.path.exists(output_dir):
    os.makedirs(output_dir)

# Save the combined DataFrame to JSONL format
combined_df.to_json(output_path, orient='records', lines=True)

print(f"Combined data saved successfully to {output_path}")
print(f"Total entries in combined DataFrame: {len(combined_df)}")
print(combined_df.head())
print(combined_df.info())

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(12, 7))
sns.countplot(data=combined_df, x='source', hue='label', palette='viridis')
plt.title('Distribution of Sources by Label (Human vs. Machine)')
plt.xlabel('Source')
plt.ylabel('Count')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()